<?php
/**
 * Generate a file config from the oauth.yml
 *
 * @author  The NetCircle
 * @version TncOauth2ServerConfigHandler.php created_at: 13-3-11 - caibaohua
 */
class TncOauth2ServerConfigHandler extends sfYamlConfigHandler
{
  /**
   * Executes this configuration handler
   *
   * @param array $configFiles An array of filesystem path to a configuration file
   *
   * @return string Data to be written to a cache file
   *
   * @throws <b>sfConfigurationException</b> If a requested configuration file does not exist or is not readable
   * @throws <b>sfParseException</b> If a requested configuration file is improperly formatted
   */
  public function execute($configFiles)
  {
    // parse the yaml
    $config = self::getConfiguration($configFiles);

    // compile data
    $retval = sprintf("<?php\n".
        "// auto-generated by TncOauth2ServerConfigHandler\n".
        "// date: %s\n\$this->oauth = %s;\n",
      date('Y/m/d H:i:s'), var_export($config, true));

    return $retval;
  }

  /**
   * @see sfConfigHandler
   */
  static public function getConfiguration(array $configFiles)
  {
    $config = self::flattenConfiguration(self::parseYamls($configFiles));

    // change all of the keys to lowercase
    $config = array_change_key_case($config);

    return $config;
  }
}
